pipeline {

    agent any
  
    stages {
        stage('Mostrar variables') {
            steps {
                echo "El valor de mi variable CUSTOM_VAR es: ${env.CUSTOM_VAR}"
            }
        }

        stage('Forzar fallo') {
            steps {
                script {
                    error("Fallo intencional para probar post-ejecución")
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline ejecutado de manera satisfactoria'
        }

        failure {
            echo 'El pipeline Fallo'
        }
    }
}