pipeline {
    agent any

    options {
        timeout(time: 2, unit: 'MINUTES')
    }
  
    stages {
        stage('Inicio de options') {
            steps {
                echo "El pipeline ejecuta una tarea con un timeout de 2 minutos"
            }
        }
        stage('Tarea por tiempo') {
            steps {
                echo "Empezando simulacion de tarea larga..."
                sleep(time: 1, unit: 'MINUTES')
            }
        }

        stage('Finalizando') {
            steps {
                echo "Tarea procesada..."
            }
        }
    }
}