services:
  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent-2
    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_AGENT_NAME: agent-2
      JENKINS_SECRET: 2d95a0b94702da4b4c8f2f2a966d5382896cd9f29e1744187ef94efa85486a9a
      JENKINS_AGENT_WORKDIR: /home/jenkins
    networks:
      - agent-net
networks:
  agent-net:
    external: true
    name: jenkins-docker_default
