pipeline {
    agent any

    stages {
        stage('Input aprobacion manual') {
            agent none
            steps {
                input message: "Continuar con el deploy ?"
                echo "Continuando con el despliegue..."
            }
        }
    }
}