pipeline {

    agent {
        docker {
            image 'node:18-alpine'
        }
    }
  
    stages {
        stage('Instalar Dependencias') {
            steps {
                sh 'npm install'
            }
        }

        stage('Ejecutar Pruebas') {
            steps {
                sh 'npm test'
            }
        }
    }
}