pipeline {
    agent any
   
    stages {
        stage('build') {
            steps {
                echo "El pipeline ejecuta una tarea de build"
            }
        }
       
        stage('Finalizando') {
            steps {
                echo "Tarea procesada..."
            }
        }
    }

    post {
        success {
            mail to: 'lcruzfarfan@gmail.com',
                 subject: 'Pipeline ejecucion correcta',
                 body: "El pipeline ${env.JOB_NAME} con el build numero ${env.BUILD_NUMBER} ha finalizado de manera correcta"
        }
    }
}