pipeline {
    agent {
        label 'agent-1'
    }
    stages {
        stage('validar hello world') {
            steps {
                sh 'echo Hello world: $(hostname)'
            }
        }
    }
}