pipeline {
    agent {
        docker {
            image 'python:3.9-alpine'
        }
    }

    stages {
        stage('Intalacion de dependencias') {
            steps {
                sh 'pip install flask'
            }
        }

        stage('Corre tests') {
            steps {
                sh 'python -m unittest'
            }
        }
    }
}